@include('front.layouts.head')
@include('front.layouts.main_header')
@include('front.layouts.main_section')
@include('front.layouts.footer')
@include('front.layouts.aside_menu')
@include('front.layouts.footer_scripts')
